# Generated by Django 2.0.3 on 2018-05-23 14:59
import os

from django.conf import settings
from django.core.files.images import ImageFile
from django.db import migrations

from app.consts import Config_Name


def init_config(apps, schema_editor):
    Config = apps.get_model("app", "Config")
    db_alias = schema_editor.connection.alias

    Config.objects.using(db_alias).bulk_create([
        # 顶部图标栏
        Config(name=Config_Name['top_ico'],
               config='{ "logo": { "img": "{%img|logo_white %}" }, "right": [ { "img": "{%fa|svg= fab fa-github|style=color:#ffffff;font-size:24px %}", "url": "https://github.com/gojuukaze" } ]}'),
        # 顶部导航栏
        Config(name=Config_Name['top_menu'], config='[ { "url": "/", "name": "首页", "img": "{% fa|fas fa-home %}" }]'),
        # 全局变量
        Config(name=Config_Name['global_value'], config='{ "title": "DeerU", "nickname": "gojuukaze"}'),
    ])


def init_img(apps, schema_editor):
    Album = apps.get_model("app", "Album")
    base_dir = settings.BASE_DIR
    with open(os.path.join(base_dir, 'logo_white.png'), 'rb')as f:
        logo_white = ImageFile(f)
        a = Album(name='logo_white')
        a.img.save('logo_white.png', logo_white)

    with open(os.path.join(base_dir, 'logo_black.png'), 'rb')as f:
        logo_black = ImageFile(f)
        a = Album(name='logo_black')
        a.img.save('logo_black.png', logo_black)


def init_content(apps, schema_editor):
    Category = apps.get_model("app", "Category")
    c = Category.objects.create(name='默认分类')


    Article = apps.get_model("app", "Article")
    base_dir = settings.BASE_DIR
    with open(os.path.join(base_dir, 'logo_white.png'), 'rb')as f:
        logo_white = ImageFile(f)
        a = Album(name='logo_white')
        a.img.save('logo_white.png', logo_white)

    with open(os.path.join(base_dir, 'logo_black.png'), 'rb')as f:
        logo_black = ImageFile(f)
        a = Album(name='logo_black')
        a.img.save('logo_black.png', logo_black)


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_config),
        migrations.RunPython(init_img)

    ]
