# Generated by Django 2.0.3 on 2018-06-01 14:47

import app.ex_fields.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180528_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('content', app.ex_fields.fields.MFroalaField(verbose_name='正文')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '单页面',
                'verbose_name_plural': '单页面',
            },
        ),
    ]
