# Generated by Django 2.2.8 on 2019-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191203_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核未通过'), (2, '审核通过')], default=0, verbose_name='状态'),
        ),
    ]
