# Generated by Django 2.0.3 on 2018-06-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_flatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='cache',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='解析后的config'),
        ),
    ]
