# Generated by Django 2.2.9 on 2020-12-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191207_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sorted_num',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
    ]
